<?php

use Illuminate\Database\Seeder;

class CgpsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cgps')->delete();
        
        \DB::table('cgps')->insert(array (
            0 => 
            array (
                'id' => 5,
                'name' => 'AEG FI',
                'registered_key' => '123456789',
                'address_1' => 'ZONE INDUSTRIELLE DE BEL AIR',
                'address_2' => NULL,
                'postal_code' => 97450,
                'city' => 'SAINT LOUIS',
                'started_at' => '2018-10-08 00:00:00',
                'created_at' => '2018-10-12 05:45:30',
                'updated_at' => '2018-10-12 05:45:30',
                'capital' => '1000',
                'registration_city' => 'SAINT LOUIS',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 3,
                'juridical_registration' => 'SAS',
                'activity' => 'CGP',
                'identifiant' => NULL,
                'contact_status' => 'Gérant',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => NULL,
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => NULL,
                'remu_fixe' => NULL,
                'network' => NULL,
                'network_yes' => NULL,
            ),
            1 => 
            array (
                'id' => 4,
                'name' => 'OPES PATRIMOINE',
                'registered_key' => '234345246',
                'address_1' => '1 rue Didier',
                'address_2' => NULL,
                'postal_code' => 94200,
                'city' => 'LA VARENNE SAINT HILAIRE',
                'started_at' => '2018-09-10 14:05:00',
                'created_at' => '2018-09-26 10:06:24',
                'updated_at' => '2018-10-12 12:44:37',
                'capital' => '30000',
                'registration_city' => 'NANTERRE',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 1,
                'juridical_registration' => 'SARL',
                'activity' => 'CGP',
                'identifiant' => NULL,
                'contact_status' => 'Gérant',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => 'EI',
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => NULL,
                'remu_fixe' => NULL,
                'network' => NULL,
                'network_yes' => NULL,
            ),
            2 => 
            array (
                'id' => 6,
                'name' => 'VYP PATRIMOINE',
                'registered_key' => '123123123',
                'address_1' => '1 RUE DU LION',
                'address_2' => NULL,
                'postal_code' => 69000,
                'city' => 'LYON',
                'started_at' => '2018-10-01 07:08:00',
                'created_at' => '2018-10-21 03:10:05',
                'updated_at' => '2018-10-21 03:10:05',
                'capital' => '1222',
                'registration_city' => 'LYON',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 1,
                'juridical_registration' => 'SARL',
                'activity' => 'CGP',
                'identifiant' => NULL,
                'contact_status' => 'Gérant',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => 'RCS',
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => NULL,
                'remu_fixe' => NULL,
                'network' => NULL,
                'network_yes' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'name' => 'PATRIMOINE OFFICE',
                'registered_key' => '111111111',
                'address_1' => '37 Avenue du Général de Gaulle',
                'address_2' => NULL,
                'postal_code' => 97434,
                'city' => 'SAINT GILLES LES BAINS',
                'started_at' => '2005-12-01 19:38:00',
                'created_at' => '2019-01-14 15:41:23',
                'updated_at' => '2019-01-14 15:41:23',
                'capital' => '1000',
                'registration_city' => 'SAINT DENIS',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 48,
                'juridical_registration' => 'EI',
                'activity' => 'CGP',
                'identifiant' => 'PAT111/7',
                'contact_status' => 'Habilité',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => 'RCS',
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => 'variable',
                'remu_fixe' => NULL,
                'network' => 'non',
                'network_yes' => NULL,
            ),
            4 => 
            array (
                'id' => 8,
                'name' => 'ConseilGestiPA',
                'registered_key' => '12312312',
                'address_1' => '1, rue de la cgp',
                'address_2' => 'Appt 5, Cité des arts',
                'postal_code' => 20121,
                'city' => 'CGPville',
                'started_at' => '2019-01-16 11:11:00',
                'created_at' => '2019-01-16 07:12:09',
                'updated_at' => '2019-01-16 07:12:09',
                'capital' => '5000',
                'registration_city' => 'Saint Denis',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 1,
                'juridical_registration' => 'EI',
                'activity' => 'CGP',
                'identifiant' => 'Con312/8',
                'contact_status' => 'Commercial',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => 'CMA',
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => 'variable',
                'remu_fixe' => '5%',
                'network' => 'non',
                'network_yes' => NULL,
            ),
            5 => 
            array (
                'id' => 9,
                'name' => 'CABINET JADOT',
                'registered_key' => '111111111',
                'address_1' => 'RFGERG',
                'address_2' => 'GERHGETG',
                'postal_code' => 67820,
                'city' => 'MULHOUSE',
                'started_at' => '2005-06-07 12:11:00',
                'created_at' => '2019-01-16 08:12:35',
                'updated_at' => '2019-01-16 08:12:35',
                'capital' => '1000',
                'registration_city' => 'METZ',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 49,
                'juridical_registration' => 'EURL',
                'activity' => 'CGP',
                'identifiant' => 'CAB111/9',
                'contact_status' => 'Commercial',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => 'RCS',
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => 'variable',
                'remu_fixe' => NULL,
                'network' => 'non',
                'network_yes' => NULL,
            ),
            6 => 
            array (
                'id' => 10,
                'name' => 'CONSEIL RETRAITE PREVOYANCE',
                'registered_key' => '413 444 209',
                'address_1' => '61, Avenue de CANTELEU',
                'address_2' => 'Batiment A',
                'postal_code' => 59650,
                'city' => 'VILLENEUVE D ASCQ',
                'started_at' => '2007-02-13 09:52:00',
                'created_at' => '2019-01-17 05:56:23',
                'updated_at' => '2019-01-18 12:34:05',
                'capital' => '108000',
                'registration_city' => 'LILLE',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 50,
                'juridical_registration' => 'SARL',
                'activity' => 'CGP',
                'identifiant' => 'COR209/10',
                'contact_status' => 'Gérant',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => 'RCS',
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => 'variable',
                'remu_fixe' => NULL,
                'network' => 'non',
                'network_yes' => NULL,
            ),
            7 => 
            array (
                'id' => 12,
                'name' => 'CGPWorld',
                'registered_key' => '123123123',
                'address_1' => 'dzdzd',
                'address_2' => 'Bat 2, 3Eme etage, Bureau E42',
                'postal_code' => 97400,
                'city' => 'Saint Denis',
                'started_at' => '2019-02-15 12:30:00',
                'created_at' => '2019-02-15 08:30:22',
                'updated_at' => '2019-02-15 08:30:22',
                'capital' => '108000',
                'registration_city' => 'Saint Denis',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 4,
                'juridical_registration' => 'SARL',
                'activity' => 'CGP',
                'identifiant' => 'CGP123/12',
                'contact_status' => 'Gérant',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => 'CMA',
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => 'variable',
                'remu_fixe' => '2%',
                'network' => 'non',
                'network_yes' => NULL,
            ),
            8 => 
            array (
                'id' => 15,
                'name' => 'CGPWorld',
                'registered_key' => '123123123',
                'address_1' => '1, rue de la modale',
                'address_2' => 'Bat 2, 3Eme etage, Bureau E42',
                'postal_code' => 97400,
                'city' => 'Saint Denis',
                'started_at' => '2019-02-15 13:22:00',
                'created_at' => '2019-02-15 09:23:06',
                'updated_at' => '2019-02-15 09:23:06',
                'capital' => '108000',
                'registration_city' => 'Saint Denis',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 2,
                'juridical_registration' => 'EI',
                'activity' => 'CGP',
                'identifiant' => 'CGP123/15',
                'contact_status' => 'Commercial',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => 'CMA',
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => 'variable',
                'remu_fixe' => '2',
                'network' => 'non',
                'network_yes' => NULL,
            ),
        ));
        
        
    }
}