<?php

use Illuminate\Database\Seeder;

class CgpsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cgps')->delete();
        
        \DB::table('cgps')->insert(array (
            0 => 
            array (
                'id' => 2,
                'name' => 'CGP test 2',
                'registered_key' => '0125461316656654654654',
                'address_1' => '1, rue de la cgp',
                'address_2' => NULL,
                'postal_code' => 12345,
                'city' => 'Saint Denis',
                'started_at' => '2018-08-14 08:29:00',
                'created_at' => '2018-09-21 04:29:31',
                'updated_at' => '2018-09-26 05:52:39',
                'capital' => '5000',
                'registration_city' => 'Saint Denis',
                'ape_key' => '12345',
                'etablishment_code' => '123',
                'contact_id' => 1,
                'juridical_registration' => 'EI',
                'activity' => 'CGP',
                'identifiant' => NULL,
                'contact_status' => 'Commercial',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => NULL,
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => NULL,
                'remu_fixe' => NULL,
                'network' => NULL,
                'network_yes' => NULL,
            ),
            1 => 
            array (
                'id' => 1,
                'name' => 'CGP test',
                'registered_key' => '1234567890',
                'address_1' => '1, rue de la cgp',
                'address_2' => NULL,
                'postal_code' => 97400,
                'city' => 'Saint Denis',
                'started_at' => '2018-07-04 10:10:00',
                'created_at' => '2018-09-20 06:15:33',
                'updated_at' => '2018-09-26 05:53:20',
                'capital' => '5000',
                'registration_city' => 'Saint Denis',
                'ape_key' => '23fZ',
                'etablishment_code' => '123',
                'contact_id' => 1,
                'juridical_registration' => 'EI',
                'activity' => 'CGP',
                'identifiant' => NULL,
                'contact_status' => 'Commercial',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => NULL,
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => NULL,
                'remu_fixe' => NULL,
                'network' => NULL,
                'network_yes' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Test6',
                'registered_key' => '545615215151',
                'address_1' => 'adressetest6',
                'address_2' => NULL,
                'postal_code' => 97400,
                'city' => 'Saint-Denis',
                'started_at' => '2018-09-10 13:11:00',
                'created_at' => '2018-09-26 09:12:04',
                'updated_at' => '2018-09-26 09:12:04',
                'capital' => '6000',
                'registration_city' => 'st-pierre',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 1,
                'juridical_registration' => 'EI',
                'activity' => 'CGP',
                'identifiant' => '656565',
                'contact_status' => 'Gérant',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => NULL,
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => NULL,
                'remu_fixe' => NULL,
                'network' => NULL,
                'network_yes' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'name' => 'AEG FI',
                'registered_key' => '123456789',
                'address_1' => 'ZONE INDUSTRIELLE DE BEL AIR',
                'address_2' => NULL,
                'postal_code' => 97450,
                'city' => 'SAINT LOUIS',
                'started_at' => '2018-10-08 00:00:00',
                'created_at' => '2018-10-12 05:45:30',
                'updated_at' => '2018-10-12 05:45:30',
                'capital' => '1000',
                'registration_city' => 'SAINT LOUIS',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 3,
                'juridical_registration' => 'SAS',
                'activity' => 'CGP',
                'identifiant' => NULL,
                'contact_status' => 'Gérant',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => NULL,
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => NULL,
                'remu_fixe' => NULL,
                'network' => NULL,
                'network_yes' => NULL,
            ),
            4 => 
            array (
                'id' => 4,
                'name' => 'OPES PATRIMOINE',
                'registered_key' => '234345246',
                'address_1' => '1 rue Didier',
                'address_2' => NULL,
                'postal_code' => 94200,
                'city' => 'LA VARENNE SAINT HILAIRE',
                'started_at' => '2018-09-10 14:05:00',
                'created_at' => '2018-09-26 10:06:24',
                'updated_at' => '2018-10-12 12:44:37',
                'capital' => '30000',
                'registration_city' => 'NANTERRE',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 1,
                'juridical_registration' => 'SARL',
                'activity' => 'CGP',
                'identifiant' => NULL,
                'contact_status' => 'Gérant',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => 'EI',
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => NULL,
                'remu_fixe' => NULL,
                'network' => NULL,
                'network_yes' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'VYP PATRIMOINE',
                'registered_key' => '123123123',
                'address_1' => '1 RUE DU LION',
                'address_2' => NULL,
                'postal_code' => 69000,
                'city' => 'LYON',
                'started_at' => '2018-10-01 07:08:00',
                'created_at' => '2018-10-21 03:10:05',
                'updated_at' => '2018-10-21 03:10:05',
                'capital' => '1222',
                'registration_city' => 'LYON',
                'ape_key' => NULL,
                'etablishment_code' => NULL,
                'contact_id' => 1,
                'juridical_registration' => 'SARL',
                'activity' => 'CGP',
                'identifiant' => NULL,
                'contact_status' => 'Gérant',
                'convention' => NULL,
                'status' => NULL,
                'kbis' => NULL,
                'rib' => NULL,
                'cni' => NULL,
                'type_registration' => 'RCS',
                'assurances' => NULL,
                'assurances_anterieures' => NULL,
                'remuneration' => NULL,
                'remu_fixe' => NULL,
                'network' => NULL,
                'network_yes' => NULL,
            ),
        ));
        
        
    }
}