<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $this->call(AddressesTableSeeder::class);
        $this->call(BanksTableSeeder::class);
        $this->call(CategoriesTableSeeder::class);
        $this->call(ContactAddressesTableSeeder::class);
        $this->call(ContactsTableSeeder::class);
        $this->call(DataTypesTableSeeder::class);
        $this->call(DataRowsTableSeeder::class);
        $this->call(MenusTableSeeder::class);
        $this->call(IntermediariesTableSeeder::class);
        $this->call(MenuItemsTableSeeder::class);
        $this->call(NatureEntitiesTableSeeder::class);
        $this->call(PagesTableSeeder::class);
        $this->call(LeaseholdersTableSeeder::class);
        $this->call(InvestorsTableSeeder::class);
        $this->call(PasswordResetsTableSeeder::class);
        $this->call(PostsTableSeeder::class);
        $this->call(RegistrationEntitiesTableSeeder::class);
        $this->call(SettingsTableSeeder::class);
        $this->call(SuppliersTableSeeder::class);
        $this->call(TauxCgpTableSeeder::class);
        $this->call(ReservationsTableSeeder::class);
        $this->call(TranslationsTableSeeder::class);
        $this->call(TypeContratsTableSeeder::class);
        $this->call(TypeEntitiesTableSeeder::class);
        $this->call(PermissionsTableSeeder::class);
        $this->call(RolesTableSeeder::class);
        $this->call(PermissionRoleTableSeeder::class);
        $this->call(UsersTableSeeder::class);
        $this->call(UserRolesTableSeeder::class);
        $this->call(VoyagerThemesTableSeeder::class);
        $this->call(VoyagerThemeOptionsTableSeeder::class);
        $this->call(CgpsTableSeeder::class);
        $this->call(SncsTableSeeder::class);
        $this->call(MandatTableSeeder::class);
        $this->call(ResetSequenceTableSeeder::class);
        $this->call(12222018AddressesTableSeeder::class);
        $this->call(12222018BanksTableSeeder::class);
        $this->call(12222018CategoriesTableSeeder::class);
        $this->call(12222018ContactAddressesTableSeeder::class);
        $this->call(12222018ContactsTableSeeder::class);
        $this->call(12222018DataTypesTableSeeder::class);
        $this->call(12222018DataRowsTableSeeder::class);
        $this->call(12222018MenusTableSeeder::class);
        $this->call(12222018IntermediariesTableSeeder::class);
        $this->call(12222018MenuItemsTableSeeder::class);
        $this->call(12222018NatureEntitiesTableSeeder::class);
        $this->call(12222018PagesTableSeeder::class);
        $this->call(12222018LeaseholdersTableSeeder::class);
        $this->call(12222018InvestorsTableSeeder::class);
        $this->call(12222018PasswordResetsTableSeeder::class);
        $this->call(12222018PostsTableSeeder::class);
        $this->call(12222018RegistrationEntitiesTableSeeder::class);
        $this->call(12222018SettingsTableSeeder::class);
        $this->call(12222018SuppliersTableSeeder::class);
        $this->call(12222018TauxCgpTableSeeder::class);
        $this->call(12222018ReservationsTableSeeder::class);
        $this->call(12222018TranslationsTableSeeder::class);
        $this->call(12222018TypeContratsTableSeeder::class);
        $this->call(12222018TypeEntitiesTableSeeder::class);
        $this->call(12222018PermissionsTableSeeder::class);
        $this->call(12222018RolesTableSeeder::class);
        $this->call(12222018PermissionRoleTableSeeder::class);
        $this->call(12222018UsersTableSeeder::class);
        $this->call(12222018UserRolesTableSeeder::class);
        $this->call(12222018VoyagerThemesTableSeeder::class);
        $this->call(12222018VoyagerThemeOptionsTableSeeder::class);
        $this->call(12222018CgpsTableSeeder::class);
        $this->call(12222018SncsTableSeeder::class);
        $this->call(12222018MandatTableSeeder::class);
    }
}
