<?php

use Illuminate\Database\Seeder;

class DevInvestisContactsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('contacts')->delete();
        
        \DB::table('contacts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'fistname' => 'Contact1',
                'lastname' => 'Test1',
                'address_1' => '1, rue du test',
                'address_2' => NULL,
                'postal_code' => 12345,
                'city' => 'testville',
                'born_on' => NULL,
                'born_in' => NULL,
                'born_in_postal' => NULL,
                'created_at' => '2018-08-23 17:34:35',
                'updated_at' => '2018-09-24 08:02:48',
                'civilite' => NULL,
                'function' => NULL,
                'tel_fixe' => NULL,
                'gsm' => NULL,
                'fax' => NULL,
                'email' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'fistname' => 'ROSSO',
                'lastname' => 'Vincent',
                'address_1' => '11 BVD DU CHAUDRON',
                'address_2' => NULL,
                'postal_code' => 97490,
                'city' => 'SAINTE CLOTILDE',
                'born_on' => '2000-03-15 13:41:00',
                'born_in' => 'AIX EN PROVENCE',
                'born_in_postal' => '13100',
                'created_at' => '2018-09-26 09:41:40',
                'updated_at' => '2018-09-26 09:41:40',
                'civilite' => NULL,
                'function' => NULL,
                'tel_fixe' => NULL,
                'gsm' => NULL,
                'fax' => NULL,
                'email' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'fistname' => 'John',
                'lastname' => 'Doe14',
                'address_1' => 'rue coco',
                'address_2' => NULL,
                'postal_code' => 97400,
                'city' => 'st denis',
                'born_on' => '1978-07-20 08:37:00',
                'born_in' => 'st pierre',
                'born_in_postal' => '97410',
                'created_at' => '2018-10-12 04:41:18',
                'updated_at' => '2018-10-12 04:41:18',
                'civilite' => NULL,
                'function' => NULL,
                'tel_fixe' => NULL,
                'gsm' => NULL,
                'fax' => NULL,
                'email' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'fistname' => 'TLILI',
                'lastname' => 'Karim',
                'address_1' => '11 LA CAILLAUDE',
                'address_2' => NULL,
                'postal_code' => 17170,
                'city' => 'LA RONDE',
                'born_on' => '1969-07-16 09:44:00',
                'born_in' => 'PARIS',
                'born_in_postal' => '75000',
                'created_at' => '2018-10-12 05:45:22',
                'updated_at' => '2018-10-12 05:45:22',
                'civilite' => NULL,
                'function' => NULL,
                'tel_fixe' => NULL,
                'gsm' => NULL,
                'fax' => NULL,
                'email' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'fistname' => 'RIVARD',
                'lastname' => 'Johan',
                'address_1' => '1 Rue didier',
                'address_2' => NULL,
                'postal_code' => 94200,
                'city' => 'LA VARENNE SAINT HILAIRE',
                'born_on' => '2018-10-12 00:00:00',
                'born_in' => 'PARIS',
                'born_in_postal' => '75000',
                'created_at' => '2018-10-12 12:39:23',
                'updated_at' => '2018-10-12 12:39:23',
                'civilite' => NULL,
                'function' => NULL,
                'tel_fixe' => NULL,
                'gsm' => NULL,
                'fax' => NULL,
                'email' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'fistname' => 'CLAIN',
                'lastname' => 'SAMUEL',
                'address_1' => '11 BVD DU CHAUDRON',
                'address_2' => NULL,
                'postal_code' => 97490,
                'city' => 'SAINTE CLOTILDE',
                'born_on' => '2018-10-01 06:59:00',
                'born_in' => 'ST DENIS',
                'born_in_postal' => '97450',
                'created_at' => '2018-10-17 02:59:26',
                'updated_at' => '2018-10-17 02:59:26',
                'civilite' => NULL,
                'function' => NULL,
                'tel_fixe' => NULL,
                'gsm' => NULL,
                'fax' => NULL,
                'email' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'fistname' => 'MORISCOT',
                'lastname' => 'Guillaume',
                'address_1' => '48 RN1 RDM',
                'address_2' => NULL,
                'postal_code' => 97412,
                'city' => 'BRAS-PANON',
                'born_on' => '1993-02-09 07:20:00',
                'born_in' => 'SAINT DENIS',
                'born_in_postal' => '97400',
                'created_at' => '2018-10-18 03:20:43',
                'updated_at' => '2018-10-18 03:20:43',
                'civilite' => NULL,
                'function' => NULL,
                'tel_fixe' => NULL,
                'gsm' => NULL,
                'fax' => NULL,
                'email' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
                'fistname' => 'ABYLON',
                'lastname' => 'Francis',
                'address_1' => '22 rue du marteau',
                'address_2' => NULL,
                'postal_code' => 97460,
                'city' => 'SAINT PAUL',
                'born_on' => '1973-07-25 07:33:00',
                'born_in' => 'SAINT DENIS',
                'born_in_postal' => '97400',
                'created_at' => '2018-10-18 03:33:57',
                'updated_at' => '2018-10-18 03:33:57',
                'civilite' => NULL,
                'function' => NULL,
                'tel_fixe' => NULL,
                'gsm' => NULL,
                'fax' => NULL,
                'email' => NULL,
            ),
            8 => 
            array (
                'id' => 11,
                'fistname' => 'VIALLON',
                'lastname' => 'Yvan',
                'address_1' => '104 AVENUE DE BOURBON',
                'address_2' => NULL,
                'postal_code' => 97434,
                'city' => 'SAINTE GILLES LES BAINS',
                'born_on' => '1972-06-20 07:09:00',
                'born_in' => 'LYON',
                'born_in_postal' => '69000',
                'created_at' => '2018-10-21 03:09:55',
                'updated_at' => '2018-10-21 03:09:55',
                'civilite' => NULL,
                'function' => NULL,
                'tel_fixe' => NULL,
                'gsm' => NULL,
                'fax' => NULL,
                'email' => NULL,
            ),
            9 => 
            array (
                'id' => 12,
                'fistname' => 'Nouveau',
                'lastname' => 'Test',
                'address_1' => 'test du focruaire d\'ajout',
                'address_2' => NULL,
                'postal_code' => 74500,
                'city' => 'testville',
                'born_on' => '1986-09-17 12:16:00',
                'born_in' => 'test',
                'born_in_postal' => '97400',
                'created_at' => '2018-10-23 08:16:58',
                'updated_at' => '2018-10-23 08:16:58',
                'civilite' => NULL,
                'function' => NULL,
                'tel_fixe' => NULL,
                'gsm' => NULL,
                'fax' => NULL,
                'email' => NULL,
            ),
            10 => 
            array (
                'id' => 13,
                'fistname' => 'MONEL',
                'lastname' => 'Christophe',
                'address_1' => '62 BVD DU CHAUDRON',
                'address_2' => 'Centre d\'affaires CADJEE',
                'postal_code' => 97490,
                'city' => 'SAINTE CLOTILDE',
                'born_on' => '1965-10-19 16:29:00',
                'born_in' => 'BOULOGNE SUR MER',
                'born_in_postal' => '62200',
                'created_at' => '2018-10-29 12:30:32',
                'updated_at' => '2018-10-29 12:30:32',
                'civilite' => '1',
                'function' => 'Président',
                'tel_fixe' => '0262348303',
                'gsm' => '0692448152',
                'fax' => '-',
                'email' => 'monelchristophe@gmail.com',
            ),
            11 => 
            array (
                'id' => 14,
                'fistname' => 'INVESTIS DOM',
                'lastname' => '-',
                'address_1' => '62 BVD DU CHAUDRON',
                'address_2' => NULL,
                'postal_code' => 97490,
                'city' => 'SAINTE CLOTILDE',
                'born_on' => NULL,
                'born_in' => NULL,
                'born_in_postal' => NULL,
                'created_at' => '2018-10-31 15:43:57',
                'updated_at' => '2018-10-31 15:43:57',
                'civilite' => NULL,
                'function' => NULL,
                'tel_fixe' => NULL,
                'gsm' => NULL,
                'fax' => NULL,
                'email' => NULL,
            ),
        ));
        
        
    }
}