<?php

use Illuminate\Database\Seeder;

class TauxCgpTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('taux_cgp')->delete();
        
        \DB::table('taux_cgp')->insert(array (
            0 => 
            array (
                'id' => 3,
                'cgps_id' => 5,
                'type_contrat_id' => 1,
                'mois_1' => '25',
                'mois_2' => '25',
                'mois_3' => '25',
                'mois_4' => '25',
                'mois_5' => '24',
                'mois_6' => '24',
                'mois_7' => '24',
                'mois_8' => '24',
                'mois_9' => '23',
                'mois_10' => '23',
                'mois_11' => '23',
                'mois_12' => '23',
                'reduction_aj' => '0.1',
                'year' => 2019,
                'created_at' => '2019-01-14 07:27:56',
                'updated_at' => '2019-01-14 07:27:56',
            ),
            1 => 
            array (
                'id' => 4,
                'cgps_id' => 7,
                'type_contrat_id' => 1,
                'mois_1' => '25',
                'mois_2' => '25',
                'mois_3' => '25',
                'mois_4' => '23',
                'mois_5' => '23',
                'mois_6' => '23',
                'mois_7' => '21',
                'mois_8' => '21',
                'mois_9' => '21',
                'mois_10' => '19',
                'mois_11' => '19',
                'mois_12' => '19',
                'reduction_aj' => '0',
                'year' => 2019,
                'created_at' => '2019-01-14 15:46:40',
                'updated_at' => '2019-01-14 15:46:40',
            ),
            2 => 
            array (
                'id' => 5,
                'cgps_id' => 7,
                'type_contrat_id' => 4,
                'mois_1' => '22',
                'mois_2' => '22',
                'mois_3' => '22',
                'mois_4' => '20',
                'mois_5' => '20',
                'mois_6' => '20',
                'mois_7' => '18',
                'mois_8' => '18',
                'mois_9' => '18',
                'mois_10' => '16',
                'mois_11' => '16',
                'mois_12' => '16',
                'reduction_aj' => '0',
                'year' => 2019,
                'created_at' => '2019-01-14 15:47:57',
                'updated_at' => '2019-01-14 15:47:57',
            ),
            3 => 
            array (
                'id' => 6,
                'cgps_id' => 7,
                'type_contrat_id' => 2,
                'mois_1' => '21',
                'mois_2' => '21',
                'mois_3' => '21',
                'mois_4' => '19',
                'mois_5' => '19',
                'mois_6' => '19',
                'mois_7' => '17',
                'mois_8' => '17',
                'mois_9' => '17',
                'mois_10' => '15',
                'mois_11' => '15',
                'mois_12' => '15',
                'reduction_aj' => '0',
                'year' => 2019,
                'created_at' => '2019-01-14 15:49:13',
                'updated_at' => '2019-01-14 15:49:13',
            ),
            4 => 
            array (
                'id' => 7,
                'cgps_id' => 7,
                'type_contrat_id' => 3,
                'mois_1' => '18',
                'mois_2' => '18',
                'mois_3' => '18',
                'mois_4' => '16',
                'mois_5' => '16',
                'mois_6' => '16',
                'mois_7' => '14',
                'mois_8' => '14',
                'mois_9' => '14',
                'mois_10' => '12',
                'mois_11' => '12',
                'mois_12' => '12',
                'reduction_aj' => '0',
                'year' => 2019,
                'created_at' => '2019-01-14 15:50:15',
                'updated_at' => '2019-01-14 15:50:15',
            ),
            5 => 
            array (
                'id' => 8,
                'cgps_id' => 8,
                'type_contrat_id' => 1,
                'mois_1' => '25',
                'mois_2' => '25',
                'mois_3' => '25',
                'mois_4' => '23',
                'mois_5' => '23',
                'mois_6' => '23',
                'mois_7' => '21',
                'mois_8' => '21',
                'mois_9' => '21',
                'mois_10' => '19',
                'mois_11' => '19',
                'mois_12' => '19',
                'reduction_aj' => '0',
                'year' => 2019,
                'created_at' => '2019-01-16 08:16:00',
                'updated_at' => '2019-01-16 08:17:20',
            ),
            6 => 
            array (
                'id' => 9,
                'cgps_id' => 10,
                'type_contrat_id' => 1,
                'mois_1' => '25',
                'mois_2' => '25',
                'mois_3' => '25',
                'mois_4' => '23',
                'mois_5' => '23',
                'mois_6' => '23',
                'mois_7' => '21',
                'mois_8' => '21',
                'mois_9' => '21',
                'mois_10' => '19',
                'mois_11' => '19',
                'mois_12' => '19',
                'reduction_aj' => '0',
                'year' => 2019,
                'created_at' => '2019-01-17 06:08:11',
                'updated_at' => '2019-01-17 06:08:11',
            ),
            7 => 
            array (
                'id' => 10,
                'cgps_id' => 10,
                'type_contrat_id' => 4,
                'mois_1' => '22',
                'mois_2' => '22',
                'mois_3' => '22',
                'mois_4' => '20',
                'mois_5' => '20',
                'mois_6' => '20',
                'mois_7' => '19',
                'mois_8' => '19',
                'mois_9' => '19',
                'mois_10' => '16',
                'mois_11' => '16',
                'mois_12' => '16',
                'reduction_aj' => '0',
                'year' => 2019,
                'created_at' => '2019-01-17 06:09:53',
                'updated_at' => '2019-01-17 06:09:53',
            ),
            8 => 
            array (
                'id' => 11,
                'cgps_id' => 10,
                'type_contrat_id' => 2,
                'mois_1' => '21',
                'mois_2' => '21',
                'mois_3' => '21',
                'mois_4' => '19',
                'mois_5' => '19',
                'mois_6' => '19',
                'mois_7' => '17',
                'mois_8' => '17',
                'mois_9' => '17',
                'mois_10' => '15',
                'mois_11' => '15',
                'mois_12' => '15',
                'reduction_aj' => '0',
                'year' => 2019,
                'created_at' => '2019-01-17 06:10:52',
                'updated_at' => '2019-01-17 06:10:52',
            ),
            9 => 
            array (
                'id' => 12,
                'cgps_id' => 10,
                'type_contrat_id' => 3,
                'mois_1' => '18',
                'mois_2' => '18',
                'mois_3' => '18',
                'mois_4' => '16',
                'mois_5' => '16',
                'mois_6' => '16',
                'mois_7' => '14',
                'mois_8' => '14',
                'mois_9' => '14',
                'mois_10' => '12',
                'mois_11' => '12',
                'mois_12' => '12',
                'reduction_aj' => '0',
                'year' => 2019,
                'created_at' => '2019-01-17 06:12:17',
                'updated_at' => '2019-01-17 06:12:17',
            ),
        ));
        
        
    }
}